(feat)O3-4206-Add ability to view patient diagnoses alongside prescribed drugs and allergies
openmrs/openmrs-esm-dispensing-app pull request #123
Opened 2024-11-18 14:05 UTC by Omoshlawi

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

As discused in [slack](https://openmrs.slack.com/archives/C02P790SM7X/p1723007479471759)
- added patient diagnoses from order visit
- used extension slot to allow implementers add more information

## Screenshots

https://github.com/user-attachments/assets/69a09202-1e64-4443-bcd2-7c49ce3c608a

## Related Issue
https://openmrs.atlassian.net/browse/O3-4206

## Other

2024-11-18 17:20 UTC, mogoodrich reviewed
Thanks so much @Omoshlawi .... will generally defer to others on this, with some thoughts:

* Looks like this only displays the diagnoses records in the visit, which likely makes sense, but would be good for others to weigh in 
* I don't love the way the diagnoses are displayed in the screen capture, but will defer to the UX team if we are following display standards correctly
* In my opinion, we should hide the diagnoses display if no diagnoses are found (instead of displaying "no diagnoses found")

I will add some others to the reviewers.

2024-11-18 17:20 UTC, mogoodrich commented on src/diagnoses/diagnoses.component.tsx
> +        <>{t('noDiagnoses', 'No diagnoses found')}</>
I would go with just displaying nothing at all if no diagnoses are found?  This is would make it more somewhat more compatible with implementations that are not yet storing diagnoses using the "encounter diagnosis" module?

2024-11-18 17:22 UTC, mogoodrich commented
Are Paul and/or Ciaran on Github and can they be flagged here to review the UI?  Otherwise, @Omoshlawi  can you add the screen capture you collected to the linked ticket and flag them there for review?  thanks!

2024-11-18 18:57 UTC, denniskigen commented
@mogoodrich Ping @paulsonder @ciaranduffy

2024-11-19 06:13 UTC, Omoshlawi commented
> Are Paul and/or Ciaran on Github and can they be flagged here to review the UI? Otherwise, @Omoshlawi can you add the screen capture you collected to the linked ticket and flag them there for review? thanks!

Okay, sure

2024-11-25 21:13 UTC, mogoodrich reviewed
Thanks so much, this is looking really good!

So I added one question/comment. Beyond that:

* eventually we want to be able to pull in the conditions and diagnoses via a standard resource provided by core or the patient chart instead of having to recreate a resource in each app that we want to display conditions/diagnoses in, but I don't want to be a blocker in getting this merged in if we aren't there yet.  Thoughts @ibacher  @denniskigen ?

* Also, overall, it would be good for someone else to get eyes on this with more O3 experience that me

2024-11-25 21:22 UTC, ibacher requested changes
Some more technical comments that what I've put on Slack.

2024-11-25 21:22 UTC, ibacher commented on src/components/empty-state.component.tsx
> +type EmptyState = {
We don't need a whole component for this. Empty states should match the design of the thing that they are the empty state for. Generic empty states are only useful in contexts where we have many similar widgets.

2024-11-25 21:22 UTC, ibacher commented on src/components/empty-state.scss
> +  row-gap: 1.5rem;
Please use Carbon spacing tokens for spacing in SCSS `row-gap`, `width`, etc.

2024-11-25 21:22 UTC, ibacher commented on src/components/empty-state.scss
> +    bottom: -0.75rem;
This looks like a hack. Why do we need this here?

2024-11-25 21:22 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +  const url = `${fhirBaseUrl}/Condition?patient=${patientUuid}&_count=100&_summary=data`;
What happens if there are more than 100? Shouldn't we have some sort of paging here?

2024-11-25 21:22 UTC, ibacher commented on src/config-schema.ts
> +  showPatientConditions: {
We also don't need _configuration_ options where things are exposed as extensions. Please remove these.

2024-11-25 21:22 UTC, ibacher commented on src/diagnoses/diagnoses.component.tsx
> +            <StructuredListRow>
Any time you call `map()` in a React component, the component _must_ have a key.

2024-11-25 21:22 UTC, ibacher commented on src/diagnoses/diagnoses.component.tsx
> +              {t('diagnoses', 'Diagnoses')} {`(${diagnoses.length})`}
Is `diagnoses.length` something that anyone asked for here? Why aren't we just using a data table or something?

2024-11-25 21:22 UTC, ibacher commented on src/routes.json
> +      "slot": "extra-patient-information-slot",
These extensions should _not_ be bound to any slot by default. That way, they are already able to be enabled or disabled by configuration.

2024-11-25 21:22 UTC, ibacher commented on src/routes.json
> +      "offline": true
Also, I'd probably just leave `offline` alone.

2025-01-10 07:04 UTC, Omoshlawi commented on src/config-schema.ts
> +    _default: false,
Ok, Removed

2025-01-10 09:17 UTC, Omoshlawi commented on src/components/empty-state.component.tsx
> +type EmptyState = {
i didn't quite understand this, kindly explain further, do you mean something like this for consistent desgin in despensing app
<img width="1419" alt="Screenshot 2025-01-10 at 12 14 21" src="https://github.com/user-attachments/assets/45980216-6e98-481d-bf62-98cc51b8dd28" />

2025-01-10 14:10 UTC, Omoshlawi commented on src/config-schema.ts
> +  showPatientConditions: {
Yes, this makes much sense, did just that, the extensions will be added from the config-app, for now to demo just added them from implementor tool

https://github.com/user-attachments/assets/2c9b2d62-507d-43bc-b41d-54254362b3a6

2025-01-10 16:16 UTC, Omoshlawi commented on src/diagnoses/diagnoses.component.tsx
> +              {t('diagnoses', 'Diagnoses')} {`(${diagnoses.length})`}
Removed and replaced by data tables, bellow is a screenshot of how it looks now
<img width="1414" alt="Screenshot 2025-01-10 at 19 15 18" src="https://github.com/user-attachments/assets/b5a92341-9d05-456e-8d09-56f18536634b" />

2025-01-10 21:07 UTC, ojwanganto commented on src/diagnoses/diagnoses.component.tsx
> +              {t('diagnoses', 'Diagnoses')} {`(${diagnoses.length})`}
Thanks, @Omoshlawi for the good work. I do think that for pharmacists, a more compressed presentation is all they need. I would suggest that you revert to the initial implementation that looked like the below:

![image](https://github.com/user-attachments/assets/b22e4280-3e45-4758-b3a1-eed906fb4627)
@ibacher and I are aligned on the same

2025-01-21 22:15 UTC, donaldkibet commented
ping @mogoodrich @ibacher

2025-01-22 05:52 UTC, ojwanganto commented on src/diagnoses/diagnoses.component.tsx
> +              {t('diagnoses', 'Diagnoses')} {`(${diagnoses.length})`}
@Omoshlawi could you kindly provide a screenshot that reverts this change?

2025-01-24 18:15 UTC, ibacher requested changes
So, as I discussed with @ojwanganto and was mentioned here, I don't think that displaying conditions and diagnoses in data tables is an effective use of screen space for pharmacists. The previous view, with tags, is much more compact and don't see a compelling reason to render tables here.

Can we please revert to using tags for diagnoses and do something similar for conditions?

2025-01-24 18:15 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +  const url = `${fhirBaseUrl}/Condition?patient=${patientUuid}&_count=100&_summary=data`;
So, `_offset` is a non-standard FHIR parameter and should not be sent in the initial request (as it's not in the actual code). With that parameter, the `next` and `previous` links are weird, without it they should work.

2025-01-24 18:19 UTC, ibacher commented
Key thing here: as a pharmacist, I need to verify that the ordered drug is a valid treatment for the patient. To do that, I need to understand what we are treating the patient for, so it's helpful to be able to see the patient's diagnoses and conditions that relate or may relate to the ordered drug. However, to do this, I just basically need a quick overview of the _names_ of any (confirmed) diagnosed conditions or problems. The table doesn't generally include any useful details and those could easily be moved to a tooltip or something similar, allowing us to better compress the data we're feeding to users so they can see it all on one screen.

2025-01-26 08:02 UTC, Omoshlawi commented on src/diagnoses/diagnoses.component.tsx
> +              {t('diagnoses', 'Diagnoses')} {`(${diagnoses.length})`}
Here is.I have reserved the configurability through implementor config-app

![Screenshot 2025-01-26 at 11 00 15](https://github.com/user-attachments/assets/0855e058-defe-450d-b8fe-9482befb1b71)

2025-01-26 08:06 UTC, Omoshlawi commented
> Key thing here: as a pharmacist, I need to verify that the ordered drug is a valid treatment for the patient. To do that, I need to understand what we are treating the patient for, so it's helpful to be able to see the patient's diagnoses and conditions that relate or may relate to the ordered drug. However, to do this, I just basically need a quick overview of the _names_ of any (confirmed) diagnosed conditions or problems. The table doesn't generally include any useful details and those could easily be moved to a tooltip or something similar, allowing us to better compress the data we're feeding to users so they can see it all on one screen.



> Key thing here: as a pharmacist, I need to verify that the ordered drug is a valid treatment for the patient. To do that, I need to understand what we are treating the patient for, so it's helpful to be able to see the patient's diagnoses and conditions that relate or may relate to the ordered drug. However, to do this, I just basically need a quick overview of the _names_ of any (confirmed) diagnosed conditions or problems. The table doesn't generally include any useful details and those could easily be moved to a tooltip or something similar, allowing us to better compress the data we're feeding to users so they can see it all on one screen.

![Screenshot 2025-01-26 at 11 00 15](https://github.com/user-attachments/assets/8a2c68b2-1d3b-464d-a18c-207ffceb72c8)

2025-01-26 08:23 UTC, Omoshlawi commented
> So, _offset is a non-standard FHIR parameter and should not be sent in the initial request (as it's not in the actual code). With that parameter, the next and previous links are weird, without it they should work.


I have removed it and here is how the `next` looks like, still weird.And also now that we are using tags, hows pagination handled??
<img width="1440" alt="Screenshot 2025-01-26 at 11 19 30" src="https://github.com/user-attachments/assets/904eb07c-48d7-45b4-b5d9-e1242c503161" />

2025-01-27 06:45 UTC, ojwanganto commented on src/diagnoses/diagnoses.component.tsx
> +              {t('diagnoses', 'Diagnoses')} {`(${diagnoses.length})`}
Please add screenshots which are a bit visible

2025-01-27 15:46 UTC, Omoshlawi commented on src/diagnoses/diagnoses.component.tsx
> +              {t('diagnoses', 'Diagnoses')} {`(${diagnoses.length})`}
<img width="1440" alt="Screenshot 2025-01-27 at 18 45 01" src="https://github.com/user-attachments/assets/d63bccc2-d35e-4ef8-98e4-3720a7107580" />

2025-01-27 16:10 UTC, ibacher commented
> I have removed it and here is how the next looks like, still weird

Weird, but correct. URLs are defined for `next` and `previous` are opaque (in the background, HAPI retains the search query in memory and returns a locator to get the next page from that in-memory instance).

>  hows pagination handled??

Precisely by following the `next` or `previous` links. You can also use the next link but substitute the number of the page for the `_getpagesoffset=<n>` parameter, but I can't guarantee that will always work. I'm pretty sure Chi-Bong wrote some helpers in core for paginated FHIR data that handle things correctly. 

By the way, if you send `_count=1`, you are asking for each page to be a single data item, which seems wasteful.

2025-02-25 13:46 UTC, makombe commented
Thanks @Omoshlawi . @ibacher Please have another look at this if it is now ready to go, thanks

2025-03-12 09:42 UTC, paulsonder commented
@makombe, thanks for sharing.

I have a few comments regarding the design in the video up top...

1. Could we change the label from 'Extra patient Info' to 'Conditions and diagnoses'?
2. It looks like the two tables are custom components, rather than reusing existing Carbon Tables or Structured lists? Could we try and use Structured lists here?

2025-03-12 18:47 UTC, ibacher commented
@makombe Can we also drop the "warning" style text for when there are no conditions or diagnoses and maybe adopt the pill styling that we have for allergies. Ideally, the conditions and diagnoses should stand out more than text noting the absence of information.

2025-03-13 10:23 UTC, Omoshlawi commented
> @makombe Can we also drop the "warning" style text for when there are no conditions or diagnoses and maybe adopt the pill styling that we have for allergies. Ideally, the conditions and diagnoses should stand out more than text noting the absence of information.

thanks @ibacher @paulsonder @makombe , here is the latest

<img width="1440" alt="Screenshot 2025-03-13 at 13 12 39" src="https://github.com/user-attachments/assets/630aa9de-645a-4e91-87b0-4a59247f852a" />

2025-03-13 10:27 UTC, Omoshlawi commented
> @makombe, thanks for sharing.
> 
> I have a few comments regarding the design in the video up top...
> 
> 1. Could we change the label from 'Extra patient Info' to 'Conditions and diagnoses'?
> 2. It looks like the two tables are custom components, rather than reusing existing Carbon Tables or Structured lists? Could we try and use Structured lists here?

Thanks @paulsonder , for suggestion (2), we (@ojwanganto @ibacher ) resolved to using ui component that covers little space hence did away with structured list and data table

2025-03-13 10:39 UTC, paulsonder commented
Hi @Omoshlawi - thanks for the update!

If there are no diagnoses, why not show an empty state or a data table / structured list?

I don't think this is the correct application of an Alert, which should call attention to something. In this case, we're giving the impression that no data is the same as some data, like an Allergy, which _we do_ want to visually emphasise. 

Space is not at a premium here, we should try to prioritise recognisable, consistent patterns for displaying information and tables and lists are used heavily in O3 and don't require custom code to be maintained.

CC @ciaranduffy

2025-03-13 11:13 UTC, Omoshlawi commented
@paulsonder , to make sure we are in one page, you suggest we have something as in which options

1.Data table see 
- [With data](https://github.com/openmrs/openmrs-esm-dispensing-app/pull/123#discussion_r1910603924)
- [Empty state](https://github.com/openmrs/openmrs-esm-dispensing-app/pull/123#discussion_r1910595320)

2. Structured list 

https://github.com/user-attachments/assets/18640401-7b59-44ee-ab7c-fc9abc508993

2025-03-17 10:09 UTC, paulsonder commented
@Omoshlawi Thanks for sharing the video... looking good... I think we should try to re-use the **Data Tile** component. I can see here the **Empty State** does, but then switches to something more custom when there is data.

You can get full design guidance on those tiles here: https://zeroheight.com/23a080e38/p/41d6df-data-tile

2025-03-17 13:53 UTC, mogoodrich commented on src/diagnoses/diagnoses.resource.ts
> +    'custom:(uuid,display,visit:(uuid,patient,encounters:(uuid,diagnoses:(uuid,display,certainty,diagnosis:(coded:(uuid,display))),encounterDatetime,encounterType:(uuid,display),encounterProviders:(u
Are we using all these elements? It looks like we are just using visit?.encounter?.diagnoses?

2025-03-18 12:10 UTC, Omoshlawi commented on src/diagnoses/diagnoses.resource.ts
> +    'custom:(uuid,display,visit:(uuid,patient,encounters:(uuid,diagnoses:(uuid,display,certainty,diagnosis:(coded:(uuid,display))),encounterDatetime,encounterType:(uuid,display),encounterProviders:(u
True, thanks @mogoodrich , fixed

2025-03-18 19:27 UTC, ibacher requested changes
Thanks @Omoshlawi! A few technical fixes and this should be good to go.

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.component.tsx
> +import { CardHeader, EmptyState } from '@openmrs/esm-patient-common-lib';
Seems preferable that we move these from common-lib to the styleguide. Adding a dependency on common-lib here is ideally not something we would do.

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.component.tsx
> +  const pageSizesOptions = useMemo(() => [3, 5, 10, 20, 50, 100], []);
`useMemo()` seems like overkill here? Why not just move `pageSizeOptions` outside of the component.

2025-03-18 19:27 UTC, ibacher commented on src/diagnoses/diagnoses.scss
> +@import '~@openmrs/esm-styleguide/src/vars';
```suggestion
@use '@openmrs/esm-styleguide/src/vars' as *;
```

2025-03-18 19:27 UTC, ibacher commented on src/prescriptions/prescription-expanded.component.tsx
> +      component: <ExtensionSlot name="extra-patient-information-slot" state={{ patientUuid, encounterUuid }} />,
```suggestion
      component: <ExtensionSlot name="dispensing-condition-and-diagnoses" state={{ patientUuid, encounterUuid }} />,
```

2025-03-18 19:27 UTC, ibacher commented on src/index.ts
> +export const patientConditions = getSyncLifecycle(PatientConditions, options);
Please use `getAsyncLifecycle()` here.

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.scss
> +@import '~@openmrs/esm-styleguide/src/vars';
```suggestion
@use '@openmrs/esm-styleguide/src/vars' as *;
```

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +    return data?.reduce<Array<Condition>>((prev, entry) => {
Wouldn't it be better to just declare this as the type for `useFhirFetchAll()` and not need the case here?

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +          status: entry?.clinicalStatus?.coding[0]?.code as any,
Why the cast to `any` here?

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +  return {
```suggestion
  }, [data]);
  
  return {
```

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +        return [...prev, condition];
```suggestion
        };
        
        return [...prev, condition];
```

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +      return prev;
```suggestion
      }
      
      return prev;
```

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +        return [...prev, condition];
Why do we do a splat and copy? It seems like `prev.push(condition)` would work just as well and not involve the need to copy things.

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.resource.ts
> +    conditions: (conditions ?? []).filter((condition) => condition.status === 'active'),
Why isn't this part of the query we're sending to the backend? Much better to filter on the backend than here.

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.component.tsx
> +  const title = t('activecondition', 'Active Condition');
```suggestion
  }, [results]);
  
  const title = t('activeCondition', 'Active Condition');
```

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.component.tsx
> +                <TableRow {...getRowProps({ row })}>
```suggestion
              {rows.map((row, i) => (
                <TableRow {...getRowProps({ row })} key={i}>
```

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.component.tsx
> +                  <TableHeader {...getHeaderProps({ header })}>{header.header}</TableHeader>
```suggestion
                {headers.map((header, i) => (
                  <TableHeader {...getHeaderProps({ header })}, key={i}>{header.header}</TableHeader>
```

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.component.tsx
> +    return (results ?? []).map((c) => ({ ...c, onsetDateTime: formatDate(parseDate(c.onsetDateTime)) }));
Why not do this in the `usePatientConditions()` hook?

2025-03-18 19:27 UTC, ibacher commented on src/conditions/conditions.component.tsx
> +import { CardHeader, EmptyState } from '@openmrs/esm-patient-common-lib';
We should ticket this for later.

2025-03-19 14:58 UTC, Omoshlawi commented on src/conditions/conditions.resource.ts
> +    return data?.reduce<Array<Condition>>((prev, entry) => {
The `useFhirFetchAll` return fhir resource which i then map to `Condition` which is a simple object with only few fields of interest

2025-03-20 20:31 UTC, ibacher commented on src/routes.json
> +      "component": "patientDiagnoses",
Shouldn't these by default be added to the slot we added for them?

2025-03-28 18:38 UTC, ibacher approved these changes

2025-03-28 18:38 UTC, merged